version: '3.3'

services:
  postgres:
    restart: always
    container_name: postgres_db
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres