run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

#  Disabled
#    - deadcode                  WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0)
#    - ifshort                   WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0)
#    - rowserrcheck              WARN [linters_context] rowserrcheck is disabled because of generics.
#    - sqlclosecheck             WARN [linters_context] sqlclosecheck is disabled because of generics.
#    - structcheck               WARN [linters_context] structcheck is disabled because of generics.
#    - varcheck                  WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0)
#    - wastedassign              WARN [linters_context] wastedassign is disabled because of generics.
